### ISSUE TITLE
Disable  requestHeaderKey: 'X-Requested-With'

### ISSUE THREAD

**Issue by kjlibsol** [nabinked/NToastNotify#102]
First -thanks for making NToastify, which I have used in many projects over the years. :)

I am facing an issue with a third-party service, that does not allow the x-requested-with header to be present - and running NToastify (for some reason I am not smart enough to understand) interferes with this.

Is there a way I can work around/configure my way around this, or is that not possible?

I am aware of this issue: https://github.com/nabinked/NToastNotify/issues/38
...but since I do not control the target server in this case, I can't reconfigure it.

On a related note, just to satisfy my curiosity: 

What is the purpose of this header in cases, where the toastr-script is loaded locally (using scriptSrc NToastifyOption)?

**Comment by os1r1s110** [comment]
@kjlibsol The header is used to determine if the request is an Ajax request or not to adapt the location where the message is saved (in memory vs tempdata) so that it can support Ajax. 

I'm not 100% sure (but 99%), but I think you could disable the Ajax support and the header might not be used anymore.

When initializing it, add the following option in Startup.cs (the `NToastNotifyOption` part):
```
.AddNToastNotifyToastr(new ToastrOptions
                {
                    ProgressBar = true,
                    PositionClass = ToastPositions.TopRight,
                    CloseButton = true,
                    TimeOut = 15000,
                    ExtendedTimeOut = 0
                }, new NToastNotifyOption()
                {
                    DisableAjaxToasts = true
                });
```

**Comment by kjlibsol** [comment]
I'll try that tomorrow and report back, thanks.

**Comment by kjlibsol** [comment]
Using disableAjaxToasts fixed the issue. thanks! :)
