### ISSUE TITLE
Does not work in .Net Core 3.1

### ISSUE THREAD

**Issue by jlwhitfill** [nabinked/NToastNotify#111]
In .NET Core 3.1, we no longer use app.AddMvc for routes anymore it uses what are called end points.  SO your code, which worked in Core 2.1 and Core 2.2, no longer works in 3.1.  The sections for the middleware:

```
        app.UseNToastNotify();
        
        app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

would translate in 3.1 to 

```
            app.UseNToastNotify();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapAreaControllerRoute(
                    name: "areas",
                    areaName: "areas",
                    pattern: "{area}/{controller=Home}/{action=Index}/{id?}");

                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
```
and this no longer works.  Everything else is set in the layout for the invoking on NToastNotify and configuration of the service (which is probably the culprit because it calls AddMVC, but Im not calling app.UseMVC in the Configure function because its not used in 3.1

```
services.AddMvc().AddNToastNotifyToastr(new ToastrOptions()
{
            ProgressBar = false,
            PositionClass = ToastPositions.BottomCenter
});
```

**Comment by AnthonyYates** [comment]
I was initially concerned by this too, but as the 3.1 samples work to demonstrate the functionality I had to dig a little deeper to figure out why. 

As it turns out [the the AddMvc source code](https://github.com/dotnet/aspnetcore/blob/a2568cbe1e8dd92d8a7976469100e564362f778e/src/Mvc/Mvc/src/MvcServiceCollectionExtensions.cs#L27) does in fact call AddRazorPages.

Hope this helps.

**Comment by AnthonyYates** [comment]
I was initially concerned by this too. However the samples (based on 3.1 works), so I dug a little deeper [into the MVC source](https://github.com/dotnet/aspnetcore/blob/a2568cbe1e8dd92d8a7976469100e564362f778e/src/Mvc/Mvc/src/MvcServiceCollectionExtensions.cs#L27) to figure out why. 

Turns out AddMvc is infact calling AddRazorPages, so using AddMvc in ConfigureServices instead of AddRazorPages is all good.

Then you can still use app.UseEndpoints in the Configure method.

**Comment by talksik** [comment]
check what the console error is. It may be that ntoastnotify is undefined which was my problem so I manually added the toastr.js from NToastNotify to my wwwroot
