### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by CybrZr00** [nabinked/NToastNotify#15]
Hi,

Thank you for taking the time to release this!

I came accross an issue that isn't really any fault of NToastNotify or yours, it's more of a VS2017 issue. 

When using NuGet in Visual Studio 2017 to install something like this, or a css framework, nuget doesn't add the css or js files to the project, meaning we have to manually download them and add them to our project. 

I'm not sure if its a bug or by design, however it does mean that your documentation is missing the instruction for users who don't realise that this issue exists.

I'm not sure it's something you should worry about, but thought I'd mention it. :)

**Comment by nabinked** [comment]
Hi @CybrZr00 

Thanks for the heads-up. 

Yes It is by design that the js/css files are not included along with the package. This is because there are so many factors that can affect the front-end side of things such as folder structure/ IDE / package-managers/ transpilers etc. So, I thought it would be better to let the developer decide how, when and where the the required files are included.

However, We could have a default setting where if specified the package will include the js/css files. That is one possible options. We can look in to it.

I should have been more specific while specifying that the toastr files have to be downloaded before referencing. I will add this information to the ReadMe file.
